Input validation
partymakers/partymaker pull request #51
Opened 2021-05-17 21:08 UTC by bkaryna

2021-05-17 22:29 UTC, ixrk requested changes
The code is OK, but the layout file is not. 

* Some fields have a hard limit on text length and some don't.
* Text length limits are all over the place. Choose one slightly higher limit for the name, one limit, also higher, for the description and one universal for the rest of fields. It doesn't need to be super optimized.
* Some fields have multiline editing enabled and some don't.

2021-05-17 22:29 UTC, ixrk commented on app/src/main/res/layout/activity_create_party.xml
> +                        app:counterMaxLength="250"
250 characters is too little for a description. Increase it to 500 or 1000.

2021-05-17 22:29 UTC, ixrk commented on app/src/main/res/layout/activity_create_party.xml
> +                        app:counterMaxLength="100"
Counter disappears after filling the field.

2021-05-18 14:18 UTC, ixrk requested changes
It's OK, but increase the max length of a description to 1000.

2021-05-18 14:20 UTC, bkaryna commented
> It's OK, but increase the max length of a description to 1000.

💩

2021-05-18 16:24 UTC, ixrk commented
> 💩

Have you got some kind of PTSD regarding maximum text length after our database course? 💩

2021-05-22 17:14 UTC, bkaryna commented
> > 💩
> 
> Have you got some kind of PTSD regarding maximum text length after our database course? 💩

I guess someone has size issues 👀

2021-05-22 17:25 UTC, ixrk approved these changes

2021-05-22 17:25 UTC, merged